### ISSUE TITLE
Rounding numbers

### ISSUE THREAD

**Issue by goodhamgupta** [versilov/matrex#13]
Hi @versilov,

I'm trying to round off numbers in a matrix. It works when my matrix contains only numbers.
```elixir
matrix = Matrex.new([[1.9893432, 2.989899]])
Matrex.apply(matrix, &Float.round(&1, 2))
#Matrex[1×2]
┌                 ┐
│    1.99    2.99 │
└                 ┘
```

However, the same function breaks when the matrix contains NaN's/Infinity.

```elixir
Matrex.new([[1.9893432, 2.989899]])
|> Matrex.divide(0)
|> Matrex.apply(&Float.round(&1, 2))

** (FunctionClauseError) no function clause matching in Matrex.apply_on_matrix/3

    The following arguments were given to Matrex.apply_on_matrix/3:

        # 1
        <<0, 0, 128, 127, 0, 0, 128, 127>>

        # 2
        #Function<6.128620087/1 in :erl_eval.expr/5>

        # 3
        <<1, 0, 0, 0, 2, 0, 0, 0>>

    Attempted function clauses (showing 2 out of 2):

        defp apply_on_matrix(<<>>, _, accumulator)
        defp apply_on_matrix(<<value::float()-little()-size(32), rest::binary()>>, function, accumulator)

    (matrex) lib/matrex.ex:693: Matrex.apply_on_matrix/3
    (matrex) lib/matrex.ex:676: Matrex.apply/2
```

I've also tried using the `Matrex.apply` function on each element as follows:

```elixir
Matrex.new([[1.9893432, 2.989899]])
|> Matrex.divide(0)
|> Matrex.apply(fn val, _row, _col -> Float.round(val, 2) end)

** (FunctionClauseError) no function clause matching in Matrex.apply_on_matrix/6

    The following arguments were given to Matrex.apply_on_matrix/6:

        # 1
        <<0, 0, 128, 127, 0, 0, 128, 127>>

        # 2
        #Function<18.128620087/3 in :erl_eval.expr/5>

        # 3
        1

        # 4
        1

        # 5
        2

        # 6
        <<1, 0, 0, 0, 2, 0, 0, 0>>

    Attempted function clauses (showing 2 out of 2):

        defp apply_on_matrix(<<>>, _, _, _, _, accumulator)
        defp apply_on_matrix(<<value::float()-little()-size(32), rest::binary()>>, function, row_index, column_index, columns, accumulator)

    (matrex) lib/matrex.ex:721: Matrex.apply_on_matrix/6
    (matrex) lib/matrex.ex:690: Matrex.apply/2
```

I've also tried the ```array``` branch for the same:

```elixir
Matrex.new([[1.9893432, 2.989899]])
|> Matrex.divide(0)
|> Matrex.apply(fn val, index -> Float.round(val, 2) end)

** (FunctionClauseError) no function clause matching in Matrex.apply_on_matrix_float32/5

    The following arguments were given to Matrex.apply_on_matrix_float32/5:

        # 1
        <<0, 0, 128, 127, 0, 0, 128, 127>>

        # 2
        #Function<12.128620087/2 in :erl_eval.expr/5>

        # 3
        {1, 1}

        # 4
        {1, 2}

        # 5
        ""

    Attempted function clauses (showing 2 out of 2):

        def apply_on_matrix_float32(<<>>, _, _, _, accumulator)
        def apply_on_matrix_float32(<<value::float()-little()-size(32), rest::binary()>>, function, pos, shape, accumulator)

    (matrex) lib/matrex.ex:1833: Matrex.apply_on_matrix_float32/5
    (matrex) lib/matrex.ex:759: Matrex.apply/2
```

Using a custom round function and checking for the type of each element also doesn't seem to work

```elixir
defmodule Custom do
  def round(value, precision) when is_float(value), do: Float.round(value, precision)

  def round(value, _precision) do
    value
  end
end

Matrex.new([[1.9893432, 2.989899]])
|> Matrex.divide(0)
|> Matrex.apply(fn val, index -> Custom.round(val, 2) end)

** (FunctionClauseError) no function clause matching in Matrex.apply_on_matrix_float32/5

    The following arguments were given to Matrex.apply_on_matrix_float32/5:

        # 1
        <<0, 0, 128, 127, 0, 0, 128, 127>>

        # 2
        #Function<12.128620087/2 in :erl_eval.expr/5>

        # 3
        {1, 1}

        # 4
        {1, 2}

        # 5
        ""

    Attempted function clauses (showing 2 out of 2):

        def apply_on_matrix_float32(<<>>, _, _, _, accumulator)
        def apply_on_matrix_float32(<<value::float()-little()-size(32), rest::binary()>>, function, pos, shape, accumulator)

    (matrex) lib/matrex.ex:1833: Matrex.apply_on_matrix_float32/5
    (matrex) lib/matrex.ex:759: Matrex.apply/2
```

Please let me know if I've missed out on any details! Thanks!

**Comment by versilov** [comment]
Hello!

Definitely a bug, fixed.

Now it passes special values (like NaN and Inf) as symbols :nan, :inf, :neg_inf to all `apply` functions. So, you can round numbers like this:

```elixir
iex> Matrex.apply(m, fn x when is_float(x) -> Float.round(x)
...> o -> o                                                 
...> end)  
```
or

```elixir
iex(2)> Matrex.apply(m, fn x when x in [:nan, :inf, :neg_inf] -> -1
...(2)> x -> Float.round(x)
...(2)> end)
```
Please, give a try.

**Comment by goodhamgupta** [comment]
Hi!

Yup, it seems to be working great! Thanks for the quick fix @versilov!

As a side note, do you have a list of tasks/features that you plan on implementing in the ```array``` branch? If you have any beginner level issues, I would be more than happy to help! 😄

**Comment by versilov** [comment]
Thank you for using this library, @goodhamgupta! You already help to debug it.

The main task, that I am stuck at right now in the array branch is displaying of multi-dimensional matrices. It does not require deep knowledge of the language, rather good algorithmic skills (which I lack).

```
  # Our goal:
  # Matrex[2×2×3×2×2]:int32
  # ┌┌┌           ┐┌           ┐┌           ┐┐┐
  # │││11111 11112││11211 11212││11311 11312│││
  # │││11121 11122││11221 11222││11321 11322│││
  # ││└           ┘└           ┘└           ┘││
  # ││┌           ┐┌           ┐┌           ┐││
  # │││12111 12112││12211 12212││12311 12312│││
  # │││12121 12122││12221 12222││12321 12322│││
  # │└└           ┘└           ┘└           ┘┘│
  # │┌┌           ┐┌           ┐┌           ┐┐│
  # │││21111 21112││21211 21212││21311 21312│││
  # │││21121 21122││21221 21222││21321 21322│││
  # ││└           ┘└           ┘└           ┘││
  # ││┌           ┐┌           ┐┌           ┐││
  # │││22111 22112││22211 22212││22311 22312│││
  # │││22121 22122││22221 22222││22321 22322│││
  # └└└           ┘└           ┘└           ┘┘┘
```

For now it's half-done, looks like this:

```
iex(3)> Matrex.random({2, 2, 3, 2, 2}, :int16)
#Matrex[2×2×3×2×2]:int16
   831   6347 ││  4338   1181 ││ 12238   3884 │││
│││  1846   3181 ││  4359  12171 ││   305   8627 │││
└        ┘
│┌┌              ┐
│││  1555   1125 ││  1560   7162 ││  4894   6021 │││
│││ 13590   3041 ││ 15878   2861 ││ 15376  15071 │││
└        ┘
│┌┌              ┐
│││ 10665   7267 ││ 11838  13686 ││  3619  15967 │││
│││ 13945  13892 ││ 14153  12669 ││ 15818   7957 │││
└        ┘
│┌┌              ┐
│││   734   3795 ││  7647   4052 ││  5177   2394 │││
│││  3746  12972 ││  5217   9171 ││ 12212   6705 │││
└        ┘
│┌┌              ┐
│││
```
